import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Import Poppins font
import "./globals.css";
import AuthProvider from "../context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";

// Import Poppins font with the desired weights
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"], // Specify just the Regular 400 weight
});

export const metadata: Metadata = {
  title: "FastFind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${poppins.className} antialiased`} // Apply the Poppins font
        >
          {children}
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
