import type { Metadata } from "next";
import { Montserrat } from "next/font/google";  // Correct import
import "./globals.css";
import AuthProvider from "../context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";

// Import Montserrat font with the desired weights
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400"], // Specify just the Regular 400 weight
});

export const metadata: Metadata = {
  title: "FastFind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${montserrat.className} antialiased`} // Apply the Montserrat class here
        >
          {children}
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
